server:
  port: 8030
spring:
  application:
    name: canary-account
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8899
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/canary_account?serverTimezone=Asia/Shanghai
    username: root
    password: Qwerty!2345
#seata客户端配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: abandon_tx_group
  service:
    vgroup-mapping:
      abandon_tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: public
      group: SEATA_GROUP
      application: seata-server

logging:
  level:
    root: info
    io.github.lagom130: debug
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
