server:
  port: 8210
spring:
  application:
    name: nydus-service
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/abandon_nydus?serverTimezone=Asia/Shanghai
    username: root
    password: Qwerty!2345
logging:
  level:
    root: info
    io.github.lagom130: debug