server:
  port: 8110
spring:
  application:
    name: canary-biz
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        dashboard: 127.0.0.1:8858
        port: 8899
#seata客户端配置
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: abandon_tx_group
  service:
    vgroup-mapping:
      abandon_tx_group: default
  registry:
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      namespace: public
      group: SEATA_GROUP
      application: seata-server

logging:
  level:
    root: info
    io.github.lagom130: debug