server:
  port: 10086
#
#spring:
#  application:
#    name: cat-canary
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#        namespace: 7665f448-995e-423e-9527-88785385205e
#      config:
#        server-addr: 127.0.0.1:8848
